"use client";

import React from 'react';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import Link from 'next/link';

interface FAQ {
  question: string;
  answer: string;
}

interface FAQSectionProps {
  title: string;
  faqs?: FAQ[];
}

const FAQSection: React.FC<FAQSectionProps> = ({
  title = "Frequently Asked Questions",
  faqs = [
    {
      question: "What kind of illustrations can I create?",
      answer: "You can create a wide range of Notion-style illustrations including people working, Some users have created interesting animal illustrations. You can browse our gallery to see other people's work."
    },
    {
      question: "How many illustrations can I generate?",
      answer: "Our free tier allows you to generate 10 illustrations. Need unlimited illustrations? Check out our flexible plans—pay only for what you use."
    },
    {
      question: "Why do some illustrations look strange?  ",
      answer: "Our illustrations are all generated by AI models, so if AI understands incorrectly, there may be unreasonable results. For this part of the content, you can write an email to tell me that I will unconditionally refund you."
    },
    {
      question: "Can I customize the illustrations?",
      answer: "Sorry, it is currently not supported to edit the generated illustrations . We are speeding up research and development."
    },
    
    {
      question: "How do I get more generation credits?",
      answer: "You can earn additional free generation credits by sharing your AI-generated work on public social media and emailing the reference links to support@imglab.dev."
    }
  ]
}) => {
  return (
    <section id="faq" className="py-20 bg-neutral-100">
      <div className="container mx-auto px-4">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-3xl md:text-4xl font-bold mb-4 gradient-text">{title}</h2>
        </div>

        <div className="max-w-3xl mx-auto">
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`} className="border-b border-gray-200">
                <AccordionTrigger className="text-left py-6 text-lg font-medium hover:text-primary hover:no-underline">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground pb-6">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>

        <div className="mt-12 text-center">
          <p className="text-muted-foreground mb-4">
            Still have questions?
          </p>
          <Link href="/about-us" className="text-primary font-medium hover:underline">
            Contact our support team
          </Link>
        </div>
      </div>
    </section>
  );
};

export default FAQSection;
